[tool.poetry]
name = "wikipedia-transform"
version = "0.1.0"
description = "Read Wikipedia data and transform them into embeddings."
authors = ["imlapps"]
readme = "README.md"
packages = [{include = "wikipedia_transform"}]

[tool.poetry.dependencies]
python = "^3.10"
isort = "^5.13.2"
black = "^24.4.2"
mypy = "^1.10.0"
ruff = "^0.4.7"
pytest = "^8.2.1"
pathlib = "^1.0.1"
pydantic = "^2.7.2"
pydantic-settings = "^2.3.0"
annotated = "^0.0.2"
unidecode = "^1.3.8"
langchain = "^0.2.1"
langchain-openai = "^0.1.8"
pytest-mock = "^3.14.0"
mypy-extensions = "^1.0.0"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
