[tool.poetry]
name = "wikipedia-transform"
version = "0.1.0"
description = "Read Wikipedia data and transform them into embeddings."
authors = ["imlapps"]
readme = "README.md"
packages = [{include = "wikipedia_transform"}]

[tool.poetry.dependencies]
python = "^3.10"
isort = "^5.13.2"
black = "^24.4.2"
mypy = "^1.10.0"
ruff = "^0.4.7"
pytest = "^8.2.1"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
